version: '3.3'
services:
  app:
    build: .
    command: sh -c "yarn install && yarn next dev"
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app:cached
