version: "3.8"
services:
  app:
    image: shoha/newport:hannahshore
    networks:
      - nginx
    command: yarn start --hostname 0.0.0.0
    ports:
      - "3000:3000"

networks:
  nginx:
    external: true
    name: nginx-config
