version: "3.8"
services:
  hannahshore-web:
    image: shoha/newport:hannahshore
    networks:
      - nginx
    command: yarn start --hostname 0.0.0.0

networks:
  nginx:
    external: true
    name: nginx-config
