version: '3.8'
services:
  app:
    build:
      context: .
      target: base
    command: bash -c 'yarn && yarn dev'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app:cached
