name: Checks
on:
  pull_request:
    branches:
      - main

jobs:
  eslint_check:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn lint

  prettier_check:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install modules
        run: yarn

      - name: Run Prettier
        run: yarn prettier -c .

  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install modules
        run: yarn

      - name: Run Prettier
        run: yarn test
