name: Deploy

on:
  push
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build latest image.
        uses: docker/build-push-action@v3
        with:
          tags: ${{secrets.DOCKER_TAGS}}
          push: true

      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: "ssh://${{secrets.DOCKER_DEPLOY_USER}}@${{secrets.DOCKER_DEPLOY_HOST}}:${{secrets.DOCKER_DEPLOY_PORT}}"
          context_name: "remote"
          ssh_cert: ${{ secrets.DOCKER_DEPLOY_KNOWN_HOST }}
          ssh_key: ${{ secrets.DOCKER_DEPLOY_KEY }}
          use_context: true

      - name: Deploy to remote host.
        run: |
          docker-compose pull
          docker-compose down --remove-orphans
          docker-compose up -d
