name: Deploy

on:
  push
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Deploy.
        uses: shoha/docker-compose-build-deploy-action
        with:
          docker-user-name: ${{ secrets.DOCKER_USER_NAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-image: ${{ secrets.DOCKER_TAGS }}
          remote-known-host-key: ${{ secrets.DOCKER_DEPLOY_KNOWN_HOST }}
          ssh-key: ${{ secrets.DOCKER_DEPLOY_KEY }}
          remote-host: ${{ secrets.DOCKER_DEPLOY_HOST }}
